module div_unit #(
  // LATENCY must be a positive divisor of 32 (1,2,4,8,16,32).  The default
  // performs four radix-2 restoring iterations per clock => 8 busy clocks.
  parameter int LATENCY = 8
) (
  input  logic                 clk,
  input  logic                 reset_n,
  input  logic                 start,
  input  riscv_pkg::mdu_op_e   op,
  input  logic [31:0]          dividend,
  input  logic [31:0]          divisor,
  output logic                 busy,
  output logic                 done,
  output logic [31:0]          result
);
  import riscv_pkg::*;

  localparam int STEPS_PER_CYCLE = 32 / LATENCY;
  localparam int CW = (LATENCY <= 1) ? 1 : $clog2(LATENCY);

  logic [CW-1:0] cycle_q;
  logic [31:0] quotient_q;
  logic [32:0] remainder_q;
  logic [31:0] divisor_q;
  mdu_op_e      op_q;
  logic         quotient_neg_q;
  logic         remainder_neg_q;
  logic         special_q;
  logic [31:0]  special_result_q;

  logic [64:0] step_state;
  logic [31:0] final_quot_mag;
  logic [31:0] final_rem_mag;
  logic [31:0] final_quot;
  logic [31:0] final_rem;
  integer k;

  function automatic logic [31:0] abs32(input logic [31:0] v);
    begin
      abs32 = v[31] ? (~v + 32'd1) : v;
    end
  endfunction

  // One unsigned radix-2 restoring division step.  The dividend magnitude is
  // initially held in quotient_q and shifted into the remainder one bit at a
  // time.  The quotient bit generated by the compare/subtract is shifted into
  // bit 0 of the quotient register.
  function automatic logic [64:0] restoring_step(
    input logic [32:0] rem_i,
    input logic [31:0] quot_i,
    input logic [31:0] div_i
  );
    logic [32:0] rem_shift;
    logic [31:0] quot_shift;
    begin
      rem_shift  = {rem_i[31:0], quot_i[31]};
      quot_shift = {quot_i[30:0], 1'b0};
      if (rem_shift >= {1'b0, div_i}) begin
        rem_shift = rem_shift - {1'b0, div_i};
        quot_shift[0] = 1'b1;
      end
      restoring_step = {rem_shift, quot_shift};
    end
  endfunction

  // Constant-count unrolling lets LATENCY trade cycle count against
  // combinational depth while remaining a genuinely iterative divider.
  always_comb begin
    step_state = {remainder_q, quotient_q};
    for (k = 0; k < STEPS_PER_CYCLE; k = k + 1)
      step_state = restoring_step(step_state[64:32], step_state[31:0], divisor_q);

    final_quot_mag = step_state[31:0];
    final_rem_mag  = step_state[63:32];
    final_quot = quotient_neg_q ? (~final_quot_mag + 32'd1) : final_quot_mag;
    final_rem  = remainder_neg_q ? (~final_rem_mag + 32'd1) : final_rem_mag;
  end

  always_ff @(posedge clk or negedge reset_n) begin
    if (!reset_n) begin
      busy <= 1'b0;
      done <= 1'b0;
      result <= 32'd0;
      cycle_q <= '0;
      quotient_q <= 32'd0;
      remainder_q <= 33'd0;
      divisor_q <= 32'd0;
      op_q <= MDU_NONE;
      quotient_neg_q <= 1'b0;
      remainder_neg_q <= 1'b0;
      special_q <= 1'b0;
      special_result_q <= 32'd0;
    end else begin
      done <= 1'b0;

      if (start && !busy) begin
        busy <= 1'b1;
        cycle_q <= '0;
        op_q <= op;
        remainder_q <= 33'd0;
        special_q <= 1'b0;
        special_result_q <= 32'd0;

        // Signed operations divide magnitudes and apply the ISA-defined signs
        // after the final iteration. Unsigned operations use the raw operands.
        if ((op == MDU_DIV) || (op == MDU_REM)) begin
          quotient_q <= abs32(dividend);
          divisor_q <= abs32(divisor);
          quotient_neg_q <= dividend[31] ^ divisor[31];
          remainder_neg_q <= dividend[31];
        end else begin
          quotient_q <= dividend;
          divisor_q <= divisor;
          quotient_neg_q <= 1'b0;
          remainder_neg_q <= 1'b0;
        end

        // RISC-V M-extension corner cases are held for the same configured
        // latency as ordinary divides so the core sees a fixed-latency unit.
        if (divisor == 32'd0) begin
          special_q <= 1'b1;
          unique case (op)
            MDU_DIV, MDU_DIVU: special_result_q <= 32'hffff_ffff;
            MDU_REM, MDU_REMU: special_result_q <= dividend;
            default:           special_result_q <= 32'd0;
          endcase
        end else if (((op == MDU_DIV) || (op == MDU_REM)) &&
                     (dividend == 32'h8000_0000) && (divisor == 32'hffff_ffff)) begin
          special_q <= 1'b1;
          special_result_q <= (op == MDU_DIV) ? 32'h8000_0000 : 32'd0;
        end
      end else if (busy) begin
        if (cycle_q == LATENCY-1) begin
          busy <= 1'b0;
          done <= 1'b1;
          cycle_q <= '0;
          if (special_q) begin
            result <= special_result_q;
          end else begin
            unique case (op_q)
              MDU_DIV,  MDU_DIVU: result <= final_quot;
              MDU_REM,  MDU_REMU: result <= final_rem;
              default:             result <= 32'd0;
            endcase
          end
        end else begin
          cycle_q <= cycle_q + 1'b1;
          if (!special_q) begin
            remainder_q <= step_state[64:32];
            quotient_q  <= step_state[31:0];
          end
        end
      end
    end
  end
endmodule
